"""
dashboard.py — render all the progress ledgers as one self-contained HTML page (P20).

You can't steer what you can't see. This reads every results/*.jsonl and produces a
single dashboard.html: HumanEval pass@1 over time vs the Sonnet-4.6 target line, the
homemade 42-task suite by category, RepoBench, and experiment verdicts. Pure stdlib +
inline SVG — open the file in any browser, no server, no deps.

  python -m bench.dashboard   (or: python cli.py dashboard)
"""
from __future__ import annotations

import json
from pathlib import Path

RESULTS = Path(__file__).resolve().parent / "results"
OUT = RESULTS / "dashboard.html"
TARGET = 0.92  # Sonnet 4.6 HumanEval pass@1


def _load(name: str) -> list[dict]:
    f = RESULTS / name
    if not f.exists():
        return []
    return [json.loads(l) for l in f.read_text(encoding="utf-8").splitlines() if l.strip()]


def _line_chart(points: list[float], target: float, w=560, h=160) -> str:
    """Inline SVG line chart of pass@1 over runs, with a target line."""
    if not points:
        return "<p>No runs yet.</p>"
    pad = 28
    n = len(points)
    xs = [pad + (w - 2 * pad) * (i / max(n - 1, 1)) for i in range(n)]
    def y(v): return h - pad - (h - 2 * pad) * v
    pts = " ".join(f"{x:.0f},{y(v):.0f}" for x, v in zip(xs, points))
    ty = y(target)
    dots = "".join(f'<circle cx="{x:.0f}" cy="{y(v):.0f}" r="3" fill="#3b82f6"/>'
                   for x, v in zip(xs, points))
    return f'''<svg viewBox="0 0 {w} {h}" width="100%" style="max-width:{w}px">
      <line x1="{pad}" y1="{ty:.0f}" x2="{w-pad}" y2="{ty:.0f}" stroke="#ef4444"
            stroke-dasharray="5,4"/><text x="{w-pad}" y="{ty-5:.0f}" fill="#ef4444"
            font-size="11" text-anchor="end">Sonnet 4.6 target {target*100:.0f}%</text>
      <polyline points="{pts}" fill="none" stroke="#3b82f6" stroke-width="2"/>{dots}
      <text x="{pad}" y="{h-6}" fill="#888" font-size="11">runs 1..{n}</text></svg>'''


def _bars(cats: dict, w=560) -> str:
    if not cats:
        return "<p>No category data.</p>"
    rows = []
    for k, v in cats.items():
        rows.append(f'''<div style="display:flex;align-items:center;gap:8px;margin:4px 0">
          <span style="width:90px;font-size:13px">{k}</span>
          <div style="flex:1;background:#1f2937;border-radius:4px;height:18px">
            <div style="width:{v*100:.0f}%;background:#10b981;height:18px;border-radius:4px"></div>
          </div><span style="width:46px;text-align:right;font-size:13px">{v*100:.0f}%</span></div>''')
    return "".join(rows)


def build() -> Path:
    he = _load("humaneval_history.jsonl")
    suite = _load("history.jsonl")
    repo = _load("repobench_history.jsonl")
    exps = _load("experiments.jsonl")

    he_pts = [r["pass1"] for r in he]
    he_now = he_pts[-1] if he_pts else 0
    last_suite = suite[-1] if suite else {}
    cats = last_suite.get("by_category", {})

    repo_rows = "".join(
        f"<tr><td>{r['ts'][:16].replace('T',' ')}</td><td>{r.get('mode','')}</td>"
        f"<td>{r['score']*100:.0f}%</td></tr>" for r in repo[-8:])
    exp_rows = "".join(
        f"<tr><td>{e.get('name','')}</td><td>{e.get('delta_pts',0):+.1f}</td>"
        f"<td>{e.get('verdict','')[:40]}</td></tr>" for e in exps[-8:])

    html = f'''<!doctype html><meta charset="utf-8"><title>Forge Dashboard</title>
<body style="font-family:system-ui;background:#0b0f17;color:#e5e7eb;max-width:680px;margin:24px auto;padding:0 16px">
<h1 style="margin:0">Forge — progress to Sonnet 4.6</h1>
<p style="color:#9ca3af">Local-first agentic coding system. Target = Sonnet 4.6 (92% HumanEval pass@1).</p>

<h2>HumanEval pass@1 over time</h2>
<div style="font-size:32px;font-weight:700">{he_now*100:.0f}%
  <span style="font-size:15px;color:#9ca3af">/ {TARGET*100:.0f}% target ·
  gap {(TARGET-he_now)*100:.0f} pts</span></div>
{_line_chart(he_pts, TARGET)}

<h2>42-task suite (latest, by category)</h2>
{_bars(cats)}
<p style="color:#9ca3af">overall {last_suite.get('overall',0)*100:.1f}%</p>

<h2>RepoBench (multi-file)</h2>
<table style="width:100%;border-collapse:collapse" cellpadding="6">
<tr style="color:#9ca3af;text-align:left"><th>when</th><th>mode</th><th>score</th></tr>
{repo_rows or '<tr><td colspan=3>no runs</td></tr>'}</table>

<h2>Experiments (research mode)</h2>
<table style="width:100%;border-collapse:collapse" cellpadding="6">
<tr style="color:#9ca3af;text-align:left"><th>name</th><th>Δpts</th><th>verdict</th></tr>
{exp_rows or '<tr><td colspan=3>no experiments</td></tr>'}</table>

<p style="color:#6b7280;margin-top:24px;font-size:12px">Generated by bench/dashboard.py
from results/*.jsonl. Re-run after each benchmark.</p></body>'''
    OUT.write_text(html, encoding="utf-8")
    return OUT


def main():
    p = build()
    print(f"dashboard -> {p}\nopen it in a browser.")


if __name__ == "__main__":
    main()
